<?
$aMenuLinks = Array(
    Array(
        "Правовые документы",
        "/documents/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Размещение информации на сайте",
        "/add_info/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "/contacts/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Вакансии",
        "/hr/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Отзывы",
        "/feedback/",
        Array(),
        Array(),
        ""
    )
);
?>